version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/web/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
