version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/johannmx/feriadosar:latest
    container_name: feriadosar-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
