
services:
  frontend:
    image: ghcr.io/johannmx/feriadosar:latest
    container_name: feriadosar-prod
    ports:
      - "80:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
