services:
  api:
    build: ./web/api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
    restart: always

  client:
    build: ./web/client
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: always
